---
version: 1.0.5-3
name: Stremio Server
slug: stremio_server
description: Run Stremio server on Home Assistant OS with hardware acceleration and VPN support
url: https://github.com/guillaume-elambert/hassio-stremio-server/tree/main/stremio
arch:
  - aarch64
  - amd64
  - armv7
startup: services
webui: "[PROTO:web_ui_protocol]://[HOST]:[PORT:8080]/"
hassio_api: true

options:
  web_ui_protocol: https
  auto_server_url: true
  auto_transcoding_profile: true
  no_cors: true
  casting_disabled: false
  disable_caching: false
  local_storage: ""
  vpn_enabled: false
  vpn_type: "openvpn"

schema:
  web_ui_protocol: list(http|https)
  server_url: str?
  auto_server_url: bool
  auto_transcoding_profile: bool
  libva_driver_name: str?
  vaapi_device: str?
  no_cors: bool
  casting_disabled: bool
  domain: str?
  cert_file: str?
  key_file: str?
  username: str?
  password: str?
  disable_caching: bool
  local_storage: str
  
  # VPN Configuration
  vpn_enabled: bool
  vpn_type: list(openvpn|wireguard)?
  vpn_service_provider: list(custom|airvpn|cyberghost|expressvpn|fastestvpn|giganews|hidemyass|ipvanish|ivpn|mullvad|nordvpn|perfect privacy|privado|private internet access|privatevpn|protonvpn|purevpn|slickvpn|surfshark|torguard|vpnsecure|vpn unlimited|vyprvpn|wevpn|windscribe)?
  vpn_config_filename: str?
  vpn_config_filename: str?
  vpn_username: str?
  vpn_password: password?
  vpn_server_countries: str?
  vpn_server_regions: str?
  vpn_server_cities: str?
  vpn_server_hostnames: str?
  vpn_port_forwarding: bool?
  debug_enabled: bool?

ports:
  8080/tcp: 8080

ports_description:
  8080/tcp: Stremio Web UI port

# Hardware acceleration and network capabilities
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/net/tun

privileged:
  - NET_ADMIN

map:
  - media:rw
  - share:rw
  - ssl:ro
  - addon_config:rw

environment:
  LIBVA_DRIVER_NAME: radeonsi
  VAAPI_DEVICE: /dev/dri/renderD128