---
name: Stremio Server
version: 1.0.0
slug: stremio_server
description: Run Stremio server on Home Assistant OS with hardware acceleration
arch:
  - aarch64
  - amd64
  - armv7
startup: services
webui: "[PROTO:web_ui_protocol]://[HOST]:[PORT:8080]/"

options:
  web_ui_protocol: https
  ipaddress: "0.0.0.0"
  auto_server_url: true
  no_cors: true
  casting_disabled: false
  webui_location: ""
  ffmpeg_bin: ""
  ffprobe_bin: ""
  app_path: ""
  domain: ""
  cert_file: ""
  username: ""
  password: ""
  disable_caching: false
  localStorage: ""

schema:
  web_ui_protocol: list(http|https)
  ipaddress: str
  server_url: str?
  auto_server_url: bool
  no_cors: bool
  casting_disabled: bool
  webui_location: str
  webui_internal_port: int?
  ffmpeg_bin: str
  ffprobe_bin: str
  app_path: str
  domain: str
  cert_file: str
  username: str
  password: str
  disable_caching: bool
  localStorage: str

ports:
  8080/tcp: 8080

ports_description:
  # 11470/tcp: Stremio server HTTP port
  # 12470/tcp: Stremio server HTTPS port
  8080/tcp: Stremio Web UI port

# Hardware acceleration configuration (matches Plex addon)
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq

map:
  - media:rw
  - share:rw
  - ssl
